### PR TITLE
ping oh dear when scheduled task has started

### PR DESCRIPTION
**Pull request by smknstd**
following https://twitter.com/freekmurze/status/1613630673281028100

I didn't test it yet with the real ohdear API but I put trust into online docs https://ohdear.app/docs/features/cron-job-monitoring

Screenshot 2023-01-13 at 10-21-31 The all-in-one monitoring tool for your entire website - Oh Dear

Can it work ?

### CODE REVIEW

**Comment by freekmurze** [comment]
In most cases, a starting event is not needed at Oh Dear to determine if a notification should be sent.

We don't want our endpoint to get this extra traffic by default. Therefore, could you put the automatic sending of the `starting` event behind a config file flag that is `false` by default?

**Comment by freekmurze** [comment]
The tests are failing. Could you take a look at that?

**Comment by smknstd** [comment]
It should be fixed

**Comment by freekmurze** [comment]
Thanks!

**Comment by smknstd** [comment]
Nice !

**Pull request merged**
